; --- asset-exact-helix-highlights ---


(setext_heading (paragraph) @markup.heading.1 (setext_h1_underline) @markup.heading.marker)
(setext_heading (paragraph) @markup.heading.2 (setext_h2_underline) @markup.heading.marker)

(atx_heading (atx_h1_marker) @markup.heading.marker) @markup.heading.1
(atx_heading (atx_h2_marker) @markup.heading.marker) @markup.heading.2
(atx_heading (atx_h3_marker) @markup.heading.marker) @markup.heading.3
(atx_heading (atx_h4_marker) @markup.heading.marker) @markup.heading.4
(atx_heading (atx_h5_marker) @markup.heading.marker) @markup.heading.5
(atx_heading (atx_h6_marker) @markup.heading.marker) @markup.heading.6

[
  (indented_code_block)
  (fenced_code_block)
] @markup.raw.block

(info_string) @label

[
  (fenced_code_block_delimiter)
] @punctuation.bracket

[
  (link_destination)
] @markup.link.url

[
  (link_label)
] @markup.link.label

[
  (list_marker_plus)
  (list_marker_minus)
  (list_marker_star)
] @markup.list.unnumbered

[
  (list_marker_dot)
  (list_marker_parenthesis)
] @markup.list.numbered

(task_list_marker_checked) @markup.list.checked
(task_list_marker_unchecked) @markup.list.unchecked

(thematic_break) @punctuation.special

[
  (block_continuation)
  (block_quote_marker)
] @punctuation.special

[
  (backslash_escape)
] @string.escape

(block_quote) @markup.quote

(pipe_table_row
  "|" @punctuation.special)
(pipe_table_header
  "|" @punctuation.special)
(pipe_table_delimiter_row) @punctuation.special

; --- completeness_definitions_semantic2 ---

(atx_heading) @definition.expression
(setext_heading) @definition.expression

; --- nvim_pinned_highlights ---

; OMEGA EXTERNAL QUERY BASELINE — CONTENT-ADDRESSED PROVENANCE
; provider=nvim-treesitter
; snapshot_marker=e82ef6ae2c3eeb96c6916b29917f96bf630b2cdb
; resolved_sha256=7b71d4994cf3968e16d033ac59d28bb034427dd41be6a057b7a2985e2dfbe5b8
; source_name=markdown

; ----- resolved nvim highlights source: markdown sha256=7b71d4994cf3968e16d033ac59d28bb034427dd41be6a057b7a2985e2dfbe5b8 -----
;From MDeiml/tree-sitter-markdown & Helix
(setext_heading
  (paragraph) @markup.heading.1
  (setext_h1_underline) @markup.heading.1)

(setext_heading
  (paragraph) @markup.heading.2
  (setext_h2_underline) @markup.heading.2)

(atx_heading
  (atx_h1_marker)) @markup.heading.1

(atx_heading
  (atx_h2_marker)) @markup.heading.2

(atx_heading
  (atx_h3_marker)) @markup.heading.3

(atx_heading
  (atx_h4_marker)) @markup.heading.4

(atx_heading
  (atx_h5_marker)) @markup.heading.5

(atx_heading
  (atx_h6_marker)) @markup.heading.6

(info_string) @label

(pipe_table_header
  (pipe_table_cell) @markup.heading)

(pipe_table_header
  "|" @punctuation.special)

(pipe_table_row
  "|" @punctuation.special)

(pipe_table_delimiter_row
  "|" @punctuation.special)

(pipe_table_delimiter_cell) @punctuation.special

; Code blocks (conceal backticks and language annotation)
(indented_code_block) @markup.raw.block

((fenced_code_block) @markup.raw.block
  (#set! priority 90))

(fenced_code_block
  (fenced_code_block_delimiter) @markup.raw.block
  (#set! conceal "")
  (#set! conceal_lines ""))

(fenced_code_block
  (info_string
    (language) @label
    (#set! conceal "")
    (#set! conceal_lines "")))

(link_destination) @markup.link.url

[
  (link_title)
  (link_label)
] @markup.link.label

((link_label)
  .
  ":" @punctuation.delimiter)

[
  (list_marker_plus)
  (list_marker_minus)
  (list_marker_star)
  (list_marker_dot)
  (list_marker_parenthesis)
] @markup.list

; NOTE: The following has been commented out due to issues with spaces in the
; list marker nodes generated by the parser. If those spaces ever get captured
; by a different node (e.g. block_continuation) we can safely re-add these
; conceals.
; ;; Conceal bullet points
; ([(list_marker_plus) (list_marker_star)]
;   @punctuation.special
;   (#offset! @punctuation.special 0 0 0 -1)
;   (#set! conceal "•"))
; ([(list_marker_plus) (list_marker_star)]
;   @punctuation.special
;   (#any-of? @punctuation.special "+" "*")
;   (#set! conceal "•"))
; ((list_marker_minus)
;   @punctuation.special
;   (#offset! @punctuation.special 0 0 0 -1)
;   (#set! conceal "—"))
; ((list_marker_minus)
;   @punctuation.special
;   (#eq? @punctuation.special "-")
;   (#set! conceal "—"))
(thematic_break) @punctuation.special

(task_list_marker_unchecked) @markup.list.unchecked

(task_list_marker_checked) @markup.list.checked

((block_quote) @markup.quote
  (#set! priority 90))

([
  (plus_metadata)
  (minus_metadata)
] @keyword.directive
  (#set! priority 90))

[
  (block_continuation)
  (block_quote_marker)
] @punctuation.special

(backslash_escape) @string.escape

(inline) @spell

; --- nvim_pinned_injections ---

; OMEGA EXTERNAL QUERY BASELINE — CONTENT-ADDRESSED PROVENANCE
; provider=nvim-treesitter
; snapshot_marker=e82ef6ae2c3eeb96c6916b29917f96bf630b2cdb
; resolved_sha256=34090de78df99b5ea84c2fbb9324f2b7c32e602043595286e83f1a1ac126073c
; source_name=markdown

; ----- resolved nvim injections source: markdown sha256=34090de78df99b5ea84c2fbb9324f2b7c32e602043595286e83f1a1ac126073c -----
(fenced_code_block
  (info_string
    (language) @injection.language)
  (code_fence_content) @injection.content)

((html_block) @injection.content
  (#set! injection.language "html")
  (#set! injection.combined)
  (#set! injection.include-children))

((minus_metadata) @injection.content
  (#set! injection.language "yaml")
  (#offset! @injection.content 1 0 -1 0)
  (#set! injection.include-children))

((plus_metadata) @injection.content
  (#set! injection.language "toml")
  (#offset! @injection.content 1 0 -1 0)
  (#set! injection.include-children))

([
  (inline)
  (pipe_table_cell)
] @injection.content
  (#set! injection.language "markdown_inline"))

; --- section_h1_h2_h3_context ---

; Generic Markdown H1 -> H2 -> H3 nested section context.
; No API/framework semantics: captures authored section headings and the H3 section span.

(section
  (atx_heading
    (atx_h1_marker)
    heading_content: (inline) @markdown.section_hierarchy.h1)
  (section
    (atx_heading
      (atx_h2_marker)
      heading_content: (inline) @markdown.section_hierarchy.h2)
    (section
      (atx_heading
        (atx_h3_marker)
        heading_content: (inline) @markdown.section_hierarchy.h3)) @markdown.section_hierarchy.h3_section) @markdown.section_hierarchy.h2_section) @markdown.section_hierarchy.h1_section

; --- section_h1_h2_h3_list_item_context ---

; Generic Markdown H1 -> H2 -> H3 nested section with a direct top-level list item in H3.
; No API/framework semantics: the list-item paragraph text is preserved as authored syntax.

(section
  (atx_heading
    (atx_h1_marker)
    heading_content: (inline) @markdown.section_item.h1)
  (section
    (atx_heading
      (atx_h2_marker)
      heading_content: (inline) @markdown.section_item.h2)
    (section
      (atx_heading
        (atx_h3_marker)
        heading_content: (inline) @markdown.section_item.h3)
      (list
        (list_item
          (paragraph
            (inline) @markdown.section_item.text) @markdown.section_item.paragraph) @markdown.section_item.list_item)) @markdown.section_item.h3_section) @markdown.section_item.h2_section) @markdown.section_item.h1_section

; --- terminal_markdown_reference_table_v1 ---
(link_reference_definition
  (link_label) @markdown.reference.label
  (link_destination) @markdown.reference.destination) @markdown.reference.definition
(pipe_table) @markdown.pipe_table
(pipe_table_header) @markdown.pipe_table.header
(pipe_table_row) @markdown.pipe_table.row
