schema_version = 1
tree_sitter_runtime = "0.25.10"
external_native_loading = false
wasm_loading = false

[[grammar]]
parser_id = "tree-sitter-json"
language = "json"
aliases = ["jsonc"]
abi_version = 14
upstream_revision = "tree-sitter/tree-sitter-json@v0.24.8"
generated_parser_package_sha256 = "4d727acca406c0020cffc6cf35516764f36c8e3dc4408e5ebe2cb35a947ec471"
node_types_identity = "62c55bcf9a3b6eeb683fa0a34b852c22aa8592ee11c26a81dbf5351d1ccc637d"
query_compatibility = "tree-sitter-abi:14;nodes:62c55bcf9a3b6eeb683fa0a34b852c22aa8592ee11c26a81dbf5351d1ccc637d"
license = "MIT"
notice = "tree-sitter-json grammar test fixture; upstream tree-sitter/tree-sitter-json@v0.24.8; license MIT"

[[grammar]]
parser_id = "tree-sitter-rust"
language = "rust"
aliases = ["rs"]
abi_version = 15
upstream_revision = "tree-sitter/tree-sitter-rust@v0.24.2"
generated_parser_package_sha256 = "439e577dbe07423ec2582ac62c7531120dbfccfa6e5f92406f93dd271a120e45"
node_types_identity = "a43a4ab2c8155d0f4a41e8d5635952dc5b7c6d23c34406c52def7800b98b48fb"
query_compatibility = "tree-sitter-abi:15;nodes:a43a4ab2c8155d0f4a41e8d5635952dc5b7c6d23c34406c52def7800b98b48fb"
license = "MIT"
notice = "tree-sitter-rust grammar test fixture; upstream tree-sitter/tree-sitter-rust@v0.24.2; license MIT"
