schema_version = 1
bundle_version = "0.7.1-npm-wasm"
parser_id = "tree-sitter-yaml"
grammar_id = "yaml"
language = "yaml"
aliases = []
upstream_repository = "https://github.com/tree-sitter-grammars/tree-sitter-yaml"
upstream_revision = "9632edc32eb86966a482fcb3c9a7f4bb78ae0ddb"
tree_sitter_abi = 14
tree_sitter_runtime = "0.25.10"
omega_runtime = ">=0.1.0"
wasm_sha256 = "e752dc21c3591df9b45692fe417d101f45d1828c28c44d79005f4066dc7e4e91"
node_types_sha256 = "1238b6c89fc6afb9723b6463a365843aa87e478025490660e5acfc9adaaf809b"
query_compatibility = "tree-sitter-abi:14;nodes:1238b6c89fc6afb9723b6463a365843aa87e478025490660e5acfc9adaaf809b"
extensions = ["yml"]
filenames = []
shebang_regexes = []
license = "MIT"
notice = "tree-sitter-yaml from npm provider @tree-sitter-grammars/tree-sitter-yaml@0.7.1; package gitHead 9632edc32eb86966a482fcb3c9a7f4bb78ae0ddb; license MIT."
bundle_size_bytes = 199538
known_injection_relationships = []
status = "experimental"
